/**
 * @file pinmux_config.h
 * @brief Pinmux for USB-to-UART+JTAG bridge (FTDI emulation)
 *
 * Overrides bl702_dualuart defaults.
 *
 * UART1 (bridge): GPIO26=TX, GPIO27=RX, GPIO24=RTS, GPIO28=DTR, GPIO25=CTS
 * UART0 (debug):  GPIO14=TX, GPIO23=RX
 * JTAG (bitbang): GPIO0=TDI, GPIO1=TDO, GPIO2=TMS, GPIO15=TCK
 * LEDs:           GPIO9=LED0, GPIO17=LED1
 * USB:            GPIO7=DM, GPIO8=DP
 */
#ifndef _PINMUX_CONFIG_H
#define _PINMUX_CONFIG_H

/* ---- JTAG MPSSE bitbang (DAP-like GPIO control) ---- */
#define CONFIG_GPIO0_FUNC  GPIO_FUN_UNUSED   /* TDI */
#define CONFIG_GPIO1_FUNC  GPIO_FUN_UNUSED   /* TDO */
#define CONFIG_GPIO2_FUNC  GPIO_FUN_UNUSED   /* TMS */
#define CONFIG_GPIO15_FUNC GPIO_FUN_UNUSED   /* TCK */

/* ---- USB ---- */
#define CONFIG_GPIO7_FUNC  GPIO_FUN_USB      /* DM */
#define CONFIG_GPIO8_FUNC  GPIO_FUN_USB      /* DP */

/* ---- LEDs ---- */
#define CONFIG_GPIO9_FUNC  GPIO_FUN_GPIO_OUTPUT_NONE  /* LED0 */
#define CONFIG_GPIO17_FUNC GPIO_FUN_GPIO_OUTPUT_NONE  /* LED1 */

/* ---- UART0 debug ---- */
#define CONFIG_GPIO14_FUNC GPIO_FUN_UART0_TX
#define CONFIG_GPIO23_FUNC GPIO_FUN_UART0_RX

/* ---- UART1 bridge (FTDI COM port) ---- */
#define CONFIG_GPIO24_FUNC GPIO_FUN_UART1_RTS
#define CONFIG_GPIO25_FUNC GPIO_FUN_UART1_CTS
#define CONFIG_GPIO26_FUNC GPIO_FUN_UART1_TX
#define CONFIG_GPIO27_FUNC GPIO_FUN_UART1_RX

/* ---- UART1 DTR (manual GPIO) ---- */
#define CONFIG_GPIO28_FUNC GPIO_FUN_GPIO_OUTPUT_NONE

/* ---- Spare ---- */
#define CONFIG_GPIO3_FUNC  GPIO_FUN_UNUSED
#define CONFIG_GPIO4_FUNC  GPIO_FUN_UNUSED
#define CONFIG_GPIO5_FUNC  GPIO_FUN_UNUSED
#define CONFIG_GPIO6_FUNC  GPIO_FUN_UNUSED
#define CONFIG_GPIO10_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO11_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO12_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO13_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO16_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO18_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO19_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO20_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO21_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO22_FUNC GPIO_FUN_UNUSED

#endif
